const http=require('http');const {spawn}=require('child_process');
const port=37891, email='smoke@atelier.local', password='Smoke@123456';
const s=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:String(port),NODE_ENV:'test',ADMIN_EMAIL:email,ADMIN_PASSWORD:password}});
function req(method,path,body='',cookie=''){return new Promise((resolve,reject)=>{const data=body?Buffer.from(JSON.stringify(body)):null;const r=http.request({hostname:'127.0.0.1',port,path,method,headers:{...(data?{'Content-Type':'application/json','Content-Length':data.length}:{}),...(cookie?{'Cookie':cookie}:{})}},x=>{let d='';x.on('data',c=>d+=c);x.on('end',()=>resolve({status:x.statusCode,headers:x.headers,body:d}))});r.on('error',reject);if(data)r.write(data);r.end()})}
(async()=>{try{await new Promise(r=>setTimeout(r,700));for(const p of ['/health','/','/admin']){const r=await req('GET',p);if(r.status!==200)throw new Error(`${p}: HTTP ${r.status}`);console.log('OK',p,r.status)}
 const pub=await req('GET','/api/public');if(pub.status!==200)throw new Error('/api/public: HTTP '+pub.status);const pd=JSON.parse(pub.body);if(!pd.products.length||!pd.gallery.length||!pd.videos.length)throw new Error('conteúdo público inicial incompleto');console.log('OK /api/public integração',pd.products.length,'produtos,',pd.gallery.length,'fotos,',pd.videos.length,'vídeos');
 const login=await req('POST','/api/auth/login',{email,password});if(login.status!==200)throw new Error('login HTTP '+login.status);const cookie=(login.headers['set-cookie']||[])[0]?.split(';')[0];if(!cookie)throw new Error('cookie de sessão ausente');console.log('OK login autenticado');
 const me=await req('GET','/api/auth/me','',cookie);if(me.status!==200)throw new Error('/api/auth/me HTTP '+me.status);console.log('OK sessão');
 const create=await req('POST','/api/products',{name:'Smoke Integração',category:'Teste',description:'Registro temporário',price:'0',status:'publicado',image:'assets/modelo-1.jpg'},cookie);if(create.status!==201)throw new Error('criação HTTP '+create.status);const id=JSON.parse(create.body).id;
 const pub2=JSON.parse((await req('GET','/api/public')).body);if(!pub2.products.some(x=>x.id===id))throw new Error('registro não chegou ao site público');console.log('OK painel → banco → site');
 const upd=await req('PUT','/api/products/'+id,{name:'Smoke Editado',status:'inativo'},cookie);if(upd.status!==200)throw new Error('edição HTTP '+upd.status);
 const pub3=JSON.parse((await req('GET','/api/public')).body);if(pub3.products.some(x=>x.id===id))throw new Error('status inativo ainda publicado');console.log('OK edição/publicação');
 const del=await req('DELETE','/api/products/'+id,'',cookie);if(del.status!==200)throw new Error('exclusão HTTP '+del.status);console.log('OK exclusão');
 console.log('SMOKE TEST PASS — integração pública + autenticação + CRUD');s.kill();process.exit(0)}catch(e){console.error('SMOKE FAIL',e.message);s.kill();process.exit(1)}})();
